version: "3.8"
services:
  app:
    container_name: app
    build: .
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
